sudo: required

services:
  - docker
  - mysql

language: python

python:
  - "3.5"

env:
  - DJANGO=1.10.2

install:
  - docker pull mysql:5.7.14
  - mkdir db
  - >
    docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS'
    -v `pwd`/db:/var/lib/mysql mysql:5.7.14
  - sleep 10 # need to give time for mysql to start
  - >
    docker run -it --name mysql-cmd --rm --link mysql:db mysql:5.7.14
    mysql -uroot -p'$3cureUS' -h db -v -e
    "CREATE DATABASE cs4501 CHARACTER SET utf8;
    CREATE DATABASE test_cs4501 CHARACTER SET utf8;
    CREATE USER 'www'@'%' IDENTIFIED BY '\$3cureUS';
    GRANT ALL PRIVILEGES ON *.* TO 'www'@'%';"

before_script:
  - docker-compose up -d
script:
  - docker ps -a
  #Call unit test in each individual container here


notifications:
    email:
        on_success: never
        on_failure: never