sudo: required

services:
  - docker
  - mysql

language: python

python:
  - "3.5"

env:
  - DJANGO=1.10.2

install:
  - docker pull mysql:5.7.14
  - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
  - docker start mysql
  - docker-compose up

script:
  - docker ps -a