sudo: required

services:
  - docker
  - mysql

language: python

python:
  - "3.5"

env:
  - DJANGO=1.10.2

install:
  - docker-compose rm
  - docker pull mysql:5.7.14
  - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
  - docker start mysql
  - docker run --name mysql-cmdline --link mysql:db mysql:5.7.14 bash
  # - "mysql -uroot -p'$3cureUS' -h db \"create user 'www'@'%' identified by '$3cureUS';\""
  # - "mysql -uroot -p'$3cureUS' -h db \"create database cs4501 character set utf8;\""
  # - "mysql -uroot -p'$3cureUS' -h db \"grant all on cs4501.* to 'www'@'%';\""
  # - docker-compose up

script:
  - docker ps -a


notifications:
    email:
        on_success: never
        on_failure: never