models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./models:/app
    # ports:
    # - "8001:8000"
    command: bash -c "python manage.py makemigrations webapp && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --working-directory ./ --reload-on-changes models/wsgi.py"


exp:
    image: tp33/django
    external_links:
      -  mysql:db
    links:
      - models:models-api
      - kafka:kafka
      - es:es
    volumes:
      - ./exp:/app
    ports:
      - "8002:8000"
    command: bash -c "pip install requests==2.11.1 && mod_wsgi-express start-server --working-directory ./ --reload-on-changes exp/wsgi.py"

web:
    image: tp33/django
    links:
      - exp:exp-api
    volumes:
      - ./web:/app
    ports:
      - "8000:8000"
    command: bash -c "pip install requests==2.11.1 && mod_wsgi-express start-server --url-alias /static ./frontend/static --working-directory ./ --reload-on-changes web/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   # ports:
   #  - "9092:8000"
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   # ports:
   #   - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   volumes:
    - ./batch:/app
   links:
      - kafka:kafka
      - es:es
   command: bash -c "python script.py && tail -f /dev/null"

spark-master:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./sparky:/app

spark-worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./sparky:/app
