models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./saynomore:/app
    ports:
      - "8001:8000"
    command: bash -c "python manage.py makemigrations webapp && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --working-directory ./ --reload-on-changes saynomore/wsgi.py"


exp:
    image: tp33/django
    links:
      - models:models-api
    volumes:
      - ./exp/:/app
    ports:
      - "8002:8000"
    command: bash -c "mod_wsgi-express start-server --working-directory ./ --reload-on-changes exp/wsgi.py"

web:
    image: tp33/django
    links:
      - exp:exp-api
    volumes:
      - ./web/:/app
    ports:
      - "8000:8000"
    command: bash -c "mod_wsgi-express start-server --working-directory ./ --reload-on-changes web/wsgi.py"