models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./models:/app
    ports:
      - "8001:8000"
    command: bash -c "python manage.py makemigrations webapp && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --working-directory ./ --reload-on-changes models/wsgi.py"


exp:
    image: tp33/django
    links:
      - models:models-api
    volumes:
      - ./exp:/app
    ports:
      - "8002:8000"
    command: bash -c "pip install requests==2.11.1 && mod_wsgi-express start-server --working-directory ./ --reload-on-changes exp/wsgi.py"

web:
    image: tp33/django
    links:
      - exp:exp-api
    volumes:
      - ./web:/app
    ports:
      - "8000:8000"
    command: bash -c "pip install requests==2.11.1 && mod_wsgi-express start-server --url-alias /static ./frontend/static --working-directory ./ --reload-on-changes web/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   command: <run a python script that pulls messages from Kafka and indexs that in ES>